[package]
name = "tmq"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]
edition = "2018"

[dependencies]
mio = "*"
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
tokio-timer = "0.2.10"
zmq = "0.9.0"
failure = "0.1"
log = "*"
[dev-dependencies]
simplelog = "*"