DROP FUNCTION IF EXISTS calculate_rescaled_ohlc(VARCHAR,VARCHAR,BIGINT,BIGINT,BIGINT);
DROP FUNCTION IF EXISTS calculate_rescaled_ohlc(VARCHAR,VARCHAR,BIGINT,BIGINT);

drop TABLE IF EXISTS cached_ohlc;

DROP FUNCTION IF EXISTS _generate_ohlc_cache(VARCHAR,VARCHAR,BIGINT,BIGINT,BIGINT);
DROP FUNCTION IF EXISTS get_ohlc_with_cache(VARCHAR,VARCHAR,BIGINT,BIGINT);