[package]
name = "actix-comm"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]
edition = "2018"


[dependencies.common]
path = "../../common"

[dependencies]
serde = "*"
actix="*"
actix_derive = "*"
failure = "*"

[dependencies.zmq]
#git = "https://github.com/semtexzv/rust-zmq"
version = "*"

[dependencies.tzmq]
package = "tokio-zmq"
rev = "master"
git = "https://github.com/semtexzv/tokio-zmq"