[package]
name = "actix-comm"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]
edition = "2018"


[dependencies.common]
path = "../../common"

[dependencies]
serde = "*"
actix = { version = "0.7", default-features=false }
actix_derive = "0.3"
failure = "*"

[dependencies.zmq]
#git = "https://github.com/semtexzv/rust-zmq"
version = "*"

[dependencies.tzmq]
package = "tokio-zmq"
rev = "master"
git = "https://github.com/semtexzv/tokio-zmq"

#[dependencies.tmq]
#path = "../tmq"