[package]
name = "actix-comm"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]
edition = "2018"


[dependencies.common]
path = "../../common"

[dependencies]
serde = "1.0"

futures = "0.1.*"
tokio = "0.1"
failure = "*"
uuid = { version = "*", features = ["v4","serde"] }

actix = "*"
actix_derive = "*"

futures-util = { path = "../futures-util"}

[dependencies.zmq]
git = "https://github.com/semtexzv/rust-zmq"

[dependencies.tzmq]
package = "tokio-zmq"
git = "https://github.com/semtexzv/tokio-zmq"