[package]
name = "db"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]
edition = "2018"

[dependencies]
common = {path = "../../common"}
serde = "*"

diesel = { version = "*", features = ["postgres", "r2d2", "chrono", "uuid"]}
diesel_migrations = "*"

r2d2="*"
r2d2-diesel="*"


cdrs = { version = "2" }
cdrs_helpers_derive = "*"


validator={ version = "*", default-features=false}
validator_derive = "*"


