[package]
name = "db"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]
edition = "2018"

[features]
default = []
scylla = ["cdrs", "cdrs_helpers_derive"]

[dependencies]
common = {path = "../../common"}
serde = "*"


diesel = { version = "*", features = ["postgres", "r2d2", "chrono", "uuid"]}
diesel_migrations = "*"

cdrs = { version = "*", optional = true}
cdrs_helpers_derive = { version = "*", optional = true }


validator={ version = "*", default-features=false}
validator_derive = "*"


