[package]
name = "db"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
common = {path = "../../common"}
serde = "*"

diesel = { version = "*", features = ["postgres", "r2d2", "chrono", "uuid"]}
diesel_migrations = "*"



validator={ version = "*", default-features=false}
validator_derive = "*"


