apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: input-svc
    labels: { app: trader}
  spec:
    selector: { layer: input }
    ports:
      - nodePort: 0
        port: 42042
        protocol: TCP
        targetPort: 42042


- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: ingest
    labels: { app: trader }
  spec:
    replicas: 1
    selector: { matchLabels: { app: trader, layer: input }}
    template:
      metadata:
        labels: { app: trader, layer: input }
      spec:
        containers:
        - name: app
          image: semtexzv/app:latest
          imagePullPolicy: Always
          command: ["/dp", "ingest"]