apiVersion: v1
kind: List
items:
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ingress
      annotations:
        kubernetes.io/ingress.class: gce
    spec:
      backend:
        serviceName: web
        servicePort: 80

  - apiVersion: v1
    kind: Service
    metadata:
      name: web
      labels: { app: trader }
    spec:
      selector: { layer: web }
      type: NodePort
      ports:
        - name: http
          port: 80

        - name: https
          port: 443


  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: web
      labels: { app: trader }
    spec:
      replicas: 1
      selector: { matchLabels: { app: trader, layer: web,  }}
      template:
        metadata:
          labels: { app: trader, layer: web }
        spec:
          containers:
            - name: app
              image: ${WEB_IMAGE}
              imagePullPolicy: Always
              command: ["/app", "web"]
              resources:
                requests:
                  cpu: 50m
              ports:
              - containerPort: 80
              - containerPort: 443
              readinessProbe:
                httpGet:
                  port: 80
                  path: /ready