[package]
name = "tokio-zmq"
description = "Provides Futures abstractions for ZeroMQ on the Tokio event-loop"
version = "0.9.0"
license = "GPL-3.0"
authors = ["asonix <asonix@asonix.dog>"]
repository = "https://git.asonix.dog/asonix/async-zmq"
readme = "README.md"
edition = "2018"
keywords = ["zmq", "zeromq", "futures", "tokio"]

[dependencies]
async-zmq-derive = { path = "../async-zmq-derive", version = "0.1" }
async-zmq-types = { path = "../async-zmq-types", version = "0.3" }
failure = "0.1"
futures = "0.1.24"
log = "0.4"
mio = "0.6"
tokio-timer = "0.2.6"
tokio-reactor = "0.1.5"
zmq = "0.9"

[dev-dependencies]
crossbeam = "0.7"
env_logger = "0.6"
tokio-executor = "0.1.4"
tokio = "0.1.8"
rand = "0.6"
