[package]
name = "apis"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]
edition = "2018"

[dependencies]
common = {path = "../../common"}

serde = "*"
serde_derive = "*"
serde_json = "*"

hmac = {version = "*", default-features = false}
sha2 = "*"
