apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: bitfinex
      labels: { app: trader }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: '9001'
        prometheus.io/path: '/metrics'
    spec:
      selector: { layer: sources, exch: bitfinex }
      ports: [ { name: metrics, port: 9001, targetPort: 9001 }]

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: bitfinex
      labels: { app: trader }
    spec:
      replicas: 1
      selector: { matchLabels: { app: trader, layer: sources, exch: bitfinex }}
      template:
        metadata:
          labels: { app: trader, layer: sources, exch: bitfinex }
        spec:
          containers:
            - name: app
              image: ${BITFINEX_IMAGE}
              imagePullPolicy: Always
              command: ["/app", "bitfinex"]
              env: [{name: "RUST_LOG", value: ${RUST_LOG}}, {name: "RUST_BACKTRACE", value: "full"}]
              #resources:
              #  requests: { cpu: 80m, memory: 100M }
              #  limits: {cpu: 90m, memory: 100M }