apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: bitfinex
      labels: { app: trader }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: '9000'
        prometheus.io/path: '/metrics'
    spec:
      selector: { layer: sources, exch: bitfinex }
      ports: [ { name: metrics, port: 9000, targetPort: 9000 }]

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: bitfinex
      labels: { app: trader }
    spec:
      replicas: 1
      strategy: { type: Recreate }
      selector: { matchLabels: { app: trader, layer: sources, exch: bitfinex }}
      template:
        metadata:
          labels: { app: trader, layer: sources, exch: bitfinex }
        spec:
          containers:
            - name: app
              image: ${BITFINEX_IMAGE}
              imagePullPolicy: Always
              command: ["/app"]
              env: [{name: "RUST_LOG", value: ${RUST_LOG}}, {name: "RUST_BACKTRACE", value: "full"}]
              resources:
                #requests: { cpu: 100m, memory: 100M }
                #limits: {cpu: 100m, memory: 100M }