apiVersion: v1
kind: List
_: &env [{name: "RUST_LOG", value: ${RUST_LOG}}, {name: "RUST_BACKTRACE", value: "full"}]
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: core
      labels: { app: trader}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: '9000'
        prometheus.io/path: '/metrics'
    spec:
      selector: { layer: core }
      ports: [ { name: metrics, port: 9000, targetPort: 9000 }]

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: core
      labels: { app: trader }
    spec:
      replicas: 1
      selector: { matchLabels: { app: trader, layer: core }}
      template:
        metadata:
          labels: { app: trader, layer: core }
        spec:
          containers:
            - name: app
              image: ${APP_IMAGE}
              imagePullPolicy: Always
              command: ["/app", "ingest"]
              env: *env
              resources:
                requests: { cpu: 100m, memory: 100M }
                limits: { cpu: 100m, memory: 100M }
