apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata: { name: eval, labels: { app: trader, layer: eval, type: worker } }
    spec:
      selector: { layer: eval, type: worker }
      ports:
        - name: eval
          port: 42042
          targetPort: 42042

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: eval
      labels: { app: trader, layer: eval, type: worker }
    spec:
      replicas: 2
      selector: { matchLabels: { app: trader, layer: eval, type: worker }}
      template:
        metadata: { labels: { app: trader, layer: eval, type: worker } }
        spec:
          containers:
            - name: app
              image: ${APP_IMAGE}
              imagePullPolicy: Always
              command: ["/app", "eval-worker"]
              env: [{name: "RUST_LOG", value: ${RUST_LOG}}]
              resources:
                requests:
                  cpu: 100m
