apiVersion: v1
kind: List
_: &env [{name: "RUST_LOG", value: ${RUST_LOG}}, {name: "RUST_BACKTRACE", value: "full"}]

items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: eval
      labels: { app: trader, layer: eval }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: '9000'
        prometheus.io/path: '/metrics'

    spec:
      selector: { layer: eval }
      ports: [ { name: metrics, port: 9000, targetPort: 9000 }]

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: eval
      labels: { app: trader, layer: eval }
    spec:
      replicas: 1
      strategy: { type: Recreate }
      selector: { matchLabels: { app: trader, layer: eval }}
      template:
        metadata: { labels: { app: trader, layer: eval } }
        spec:
          containers:
            - name: app
              image: ${EVAL_IMAGE}
              imagePullPolicy: Always
              command: ["/app"]
              env: *env
              #resources: { requests: { cpu: 100m, memory: 100M }, limits: { cpu: 100m, memory: 100M } }

