apiVersion: v1
kind: List
_: &env [{name: "RUST_LOG", value: ${RUST_LOG}}]

items:
  ## Eval workers
  - apiVersion: v1
    kind: Service
    metadata: { name: eval, labels: { app: trader, layer: eval, type: balancer } }
    spec:
      selector: { layer: eval, type: balancer }
      ports:
        - name: eval
          port: 42042
          targetPort: 42042

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: eval-balancer
      labels: { app: trader, layer: eval, type: balancer }
    spec:
      replicas: 1
      selector: { matchLabels: { app: trader, layer: eval, type: balancer }}
      template:
        metadata: { labels: { app: trader, layer: eval, type: balancer } }
        spec:
          containers:
            - name: app
              image: ${APP_IMAGE}
              imagePullPolicy: Always
              command: ["/app", "eval-balancer"]
              env: *env
              resources: { requests: { cpu: 100m }, limits: { cpu: 200m } }

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: eval
      labels: { app: trader, layer: eval, type: worker }
    spec:
      replicas: 2
      selector: { matchLabels: { app: trader, layer: eval, type: worker }}
      template:
        metadata: { labels: { app: trader, layer: eval, type: worker } }
        spec:
          containers:
            - name: app
              image: ${APP_IMAGE}
              imagePullPolicy: Always
              command: ["/app", "eval-worker"]
              env: *env
              resources: { requests: { cpu: 200m }, limits: { cpu: 200m } }
