apiVersion: v1
kind: List
_: &env [{name: "RUST_LOG", value: ${RUST_LOG}}, {name: "RUST_BACKTRACE", value: "full"}]

items:
  - apiVersion: v1
    kind: Service
    metadata: { name: eval, labels: { app: trader, layer: eval } }
    spec:
      selector: { layer: eval }
      ports:
        - name: eval
          port: 42042
          targetPort: 42042

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: eval
      labels: { app: trader, layer: eval }
    spec:
      replicas: 1
      selector: { matchLabels: { app: trader, layer: eval }}
      template:
        metadata: { labels: { app: trader, layer: eval } }
        spec:
          containers:
            - name: app
              image: ${APP_IMAGE}
              imagePullPolicy: Always
              command: ["/app", "evaluator"]
              env: *env
              #resources: { requests: { cpu: 100m, memory: 100M }, limits: { cpu: 100m, memory: 100M } }

