apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: trader-pg-config
  data:
    POSTGRES_DB: trader
    POSTGRES_USER: trader
    POSTGRES_PASSWORD: trader
    PGDATA: /pgdata/pgdata

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: trader-db
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi

- kind: Service
  apiVersion: v1
  metadata:
    name: postgres
    labels: { app: trader }
  spec:
    ports: [ { port: 5432 } ]
    selector: { app: trader, layer: storage }


- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: postgres
    labels: { app: trader }
  spec:
    replicas: 1
    strategy: { type: Recreate }
    selector: { matchLabels: { app: trader, layer: storage }}
    template:
      metadata:
        labels: { app: trader, layer: storage }
      spec:
        containers:
          - name: postgres
            image: timescale/timescaledb:1.2.1-pg11-oss
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 5432
            envFrom:
              - configMapRef: { name: trader-pg-config }
            volumeMounts:
              - mountPath: /pgdata
                name: postgresdb
            resources:
              requests:
                cpu: 100m
                memory: 300Mi
              limits:
                cpu: 150m
                memory: 450Mi
        volumes:
          - name: postgresdb
            persistentVolumeClaim:
              claimName: trader-db


