apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: trader-pg-config
      labels: { app: trader }
    data:
      POSTGRES_DB: trader
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trader
      PGDATA: /pgdata/pgdata

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: trader-pg-db
      labels: { app: trader }
    spec:
      storageClassName: do-block-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi

  - kind: Service
    apiVersion: v1
    metadata:
      name: postgres
      labels: { app: trader }
    spec:
      ports: [ { port: 5432 } ]
      selector: { app: trader, layer: storage }


  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: postgres
      labels: { app: trader }
    spec:
      replicas: 1
      strategy: { type: Recreate }
      selector: { matchLabels: { app: trader, layer: storage }}
      template:
        metadata:
          labels: { app: trader, layer: storage }
        spec:
          containers:
            - name: postgres
              image: timescale/timescaledb:1.4.1-pg11
              imagePullPolicy: Always
              args: [ "-N", "800" ]
              ports:
                - containerPort: 5432
              envFrom:
                - configMapRef: { name: trader-pg-config }
              volumeMounts:
                - mountPath: /pgdata
                  name: postgresdb
              resources:
                requests: { cpu: 200m, memory: 500Mi }
                limits: { cpu: 200m, memory: 500Mi }
          volumes:
            - name: postgresdb
              persistentVolumeClaim:
                claimName: trader-pg-db


