apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp
  labels:
    app: tp
spec:
  replicas: 1  # only one replica
  selector: { matchLabels: { app: trader }}
  template:
    metadata:
      labels: { name: tp, app: trader }
    spec:
      containers:
        - name: tp
          image: datawire/telepresence-k8s:0.102  # new image
          resources:
            #requests: { cpu: 20m, memory: 80M }
            #limits: { cpu: 20m, memory: 80M }