apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: web
      labels: { app: trader }
    spec:
      selector: { layer: web }
      type: NodePort
      externalIPs: ["67.207.76.239"]
      ports:
        - name: http
          port: 8000
          nodePort: 30000
          targetPort: 8000

        - name: https
          port: 443
          nodePort: 30001
          targetPort: 443



  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: web
      labels: { app: trader }
    spec:
      replicas: 1
      selector: { matchLabels: { app: trader, layer: web,  }}
      template:
        metadata:
          labels: { app: trader, layer: web }
        spec:
          containers:
            - name: app
              image: ${WEB_IMAGE}
              imagePullPolicy: Always
              command: ["/app", "web"]
              env: [{name: "RUST_LOG", value: ${RUST_LOG}}]
              resources:
                requests:
                  cpu: 20m
              ports:
              - containerPort: 8000
              - containerPort: 443
              readinessProbe:
                httpGet:
                  port: 8000
                  path: /ready