apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: web
      labels: { app: trader }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: '9000'
        prometheus.io/path: '/metrics'
    spec:
      selector: { layer: web }
      type: NodePort
      ports:
        - { name: metrics, port: 9000, targetPort: 9000 }
        - name: http
          port: 8000
          nodePort: 32000
          targetPort: 8000

        - name: https
          port: 443
          nodePort: 32001
          targetPort: 443

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: web
      labels: { app: trader }
    spec:
      replicas: 1
      selector: { matchLabels: { app: trader, layer: web,  }}
      template:
        metadata:
          labels: { app: trader, layer: web }
        spec:
          containers:
            - name: app
              image: ${WEB_IMAGE}
              imagePullPolicy: Always
              command: ["/app", "web"]
              env: [{name: "RUST_LOG", value: ${RUST_LOG}}, {name: "WEBAPP_ROOT", value: "/src/app/dist"}]
              resources:
                requests: { cpu: 100m, memory: 80M }
                limits: { cpu: 100m, memory: 80M   }
              ports:
              - containerPort: 8000
              - containerPort: 443
              readinessProbe:
                httpGet:
                  port: 8000
                  path: /ready