[package]
name = "csdb"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]
edition = "2018"

[features]
default = []


[dependencies]
common = {path = "../../common"}
serde = "*"


cdrs = { version = "2" }
cdrs_helpers_derive = "*"
