# src: https://github.com/helm/charts/tree/master/stable/prometheus
server:
  extraArgs: {}
  resources:
    requests: { cpu: 300m, memory: 400M }
    limits: { cpu: 300m, memory: 400M   }
  global:
    scrape_interval: 2m
    evaluation_interval: 2m

alertmanager:
  enabled: false

pushgateway:
  enabled: false