[package]
name = "common"
version = "0.0.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static= "*"
log = "*"
failure = "*"
failure_derive="*"
bytes = { version = "0.4", features = ["serde"] }
futures = "0.1"
url = "*"

actix = "0.7"

