[package]
name = "web"
version = "0.1.0"
authors = ["Michal Hornický <semtexzv@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies.common]
path = "../common"

[dependencies]
serde = "*"
db = { path = "../deps/db" }

mime = "0.3"
mime_guess = "2.0.1"

djangohashers = "^0.3"