export const POST_ONE_SUCCESS = 'POST_ONE_SUCCESS';

export const LOAD_ONE_SUCCESS = 'LOAD_ONE_SUCCESS';
export const LOAD_ALL_SUCCESS = 'LOAD_ALL_SUCCESS';
export const DELETE_ONE_SUCCESS = 'DELETE_ONE_SUCCESS';

export const AUTH_OK = "AUTH_OK";
export const AUTH_INVALID = 'AUTH_INVALID';
